/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shutdown_timer;

import java.awt.Color;
import java.awt.Dialog;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author nqs19
 */
public class Shutdown_Timer extends javax.swing.JFrame {
int xx;
int xy;
int mins,hours,seconds;
    /**
     * Creates new form Shutdown_Timer
     */
    public Shutdown_Timer() {
        initComponents();
        this.setLocationRelativeTo(null);//Center screen
        btnCancel.setEnabled(false);
        btnPause.setEnabled(false);
        btnResume.setEnabled(false);
        JOptionPane.showConfirmDialog(null, "Lập trình bởi Duy Bé","GIỚI THIỆU",JOptionPane.PLAIN_MESSAGE,1);
        for(int i = 0; i<=23;i++)
        {
            if(i<10) cbHours.addItem("0"+i);
            else cbHours.addItem(i);
        }
        for(int i = 0; i<=59;i++)
        {
            if(i<10) cbMins.addItem("0"+i);
            else cbMins.addItem(i);
        }
        for(int i = 0; i<=59;i++)
        {
            if(i<10) cbSeconds.addItem("0"+i);
            else cbSeconds.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain = new javax.swing.JPanel();
        PanelTitle = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PanelClock = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        cbHours = new javax.swing.JComboBox();
        cbMins = new javax.swing.JComboBox();
        cbSeconds = new javax.swing.JComboBox();
        lblSeconds = new javax.swing.JLabel();
        lblMins = new javax.swing.JLabel();
        lblHours = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        btnResume = new javax.swing.JButton();
        PanelColor = new javax.swing.JPanel();
        pBlue = new javax.swing.JPanel();
        pDeep_Purple = new javax.swing.JPanel();
        pIndigo = new javax.swing.JPanel();
        pPurple = new javax.swing.JPanel();
        pPink = new javax.swing.JPanel();
        pRed = new javax.swing.JPanel();
        pLight_Blue = new javax.swing.JPanel();
        pCyan = new javax.swing.JPanel();
        pTeal = new javax.swing.JPanel();
        pGreen = new javax.swing.JPanel();
        pLight_Green = new javax.swing.JPanel();
        pLime = new javax.swing.JPanel();
        pYellow = new javax.swing.JPanel();
        pAmber = new javax.swing.JPanel();
        pOrange = new javax.swing.JPanel();
        pDeep_Orange = new javax.swing.JPanel();
        pGray = new javax.swing.JPanel();
        pLight_Blue6 = new javax.swing.JPanel();
        btnPause = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelMain.setBackground(new java.awt.Color(96, 125, 139));
        PanelMain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelMainMouseDragged(evt);
            }
        });
        PanelMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelMainMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PanelMainMouseReleased(evt);
            }
        });

        PanelTitle.setBackground(new java.awt.Color(69, 90, 100));

        btnExit.setBackground(new java.awt.Color(69, 90, 100));
        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(69, 90, 100));
        btnMinimize.setText("__");
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ĐẶT GIỜ TẮT MÁY");

        javax.swing.GroupLayout PanelTitleLayout = new javax.swing.GroupLayout(PanelTitle);
        PanelTitle.setLayout(PanelTitleLayout);
        PanelTitleLayout.setHorizontalGroup(
            PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTitleLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelTitleLayout.setVerticalGroup(
            PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanelClock.setBackground(new java.awt.Color(96, 125, 139));

        cbHours.setBackground(new java.awt.Color(96, 125, 139));
        cbHours.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHoursActionPerformed(evt);
            }
        });

        cbMins.setBackground(new java.awt.Color(96, 125, 139));
        cbMins.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbMins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMinsActionPerformed(evt);
            }
        });

        cbSeconds.setBackground(new java.awt.Color(96, 125, 139));
        cbSeconds.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbSeconds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSecondsActionPerformed(evt);
            }
        });

        lblSeconds.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblSeconds.setText("00");

        lblMins.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblMins.setText("00");

        lblHours.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblHours.setText("00");

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl2.setText(":");

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl1.setText(":");

        javax.swing.GroupLayout PanelClockLayout = new javax.swing.GroupLayout(PanelClock);
        PanelClock.setLayout(PanelClockLayout);
        PanelClockLayout.setHorizontalGroup(
            PanelClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClockLayout.createSequentialGroup()
                .addGroup(PanelClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClockLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelClockLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PanelClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbHours, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelClockLayout.createSequentialGroup()
                                .addComponent(lblHours, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(PanelClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbMins, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMins, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelClockLayout.createSequentialGroup()
                                .addComponent(lbl2)
                                .addGap(14, 14, 14)
                                .addComponent(lblSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        PanelClockLayout.setVerticalGroup(
            PanelClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelClockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeconds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelClockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHours, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSeconds, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMins, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnCancel.setBackground(new java.awt.Color(96, 125, 139));
        btnCancel.setText("DỪNG");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnRun.setBackground(new java.awt.Color(96, 125, 139));
        btnRun.setText("CHẠY");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        btnResume.setBackground(new java.awt.Color(96, 125, 139));
        btnResume.setText("TIẾP TỤC");
        btnResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumeActionPerformed(evt);
            }
        });

        PanelColor.setBackground(new java.awt.Color(96, 125, 139));

        pBlue.setBackground(new java.awt.Color(25, 118, 210));
        pBlue.setPreferredSize(new java.awt.Dimension(50, 50));
        pBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pBlueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pBlueLayout = new javax.swing.GroupLayout(pBlue);
        pBlue.setLayout(pBlueLayout);
        pBlueLayout.setHorizontalGroup(
            pBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pBlueLayout.setVerticalGroup(
            pBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pDeep_Purple.setBackground(new java.awt.Color(81, 45, 168));
        pDeep_Purple.setPreferredSize(new java.awt.Dimension(50, 50));
        pDeep_Purple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pDeep_PurpleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pDeep_PurpleLayout = new javax.swing.GroupLayout(pDeep_Purple);
        pDeep_Purple.setLayout(pDeep_PurpleLayout);
        pDeep_PurpleLayout.setHorizontalGroup(
            pDeep_PurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pDeep_PurpleLayout.setVerticalGroup(
            pDeep_PurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pIndigo.setBackground(new java.awt.Color(48, 63, 159));
        pIndigo.setPreferredSize(new java.awt.Dimension(50, 50));
        pIndigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pIndigoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pIndigoLayout = new javax.swing.GroupLayout(pIndigo);
        pIndigo.setLayout(pIndigoLayout);
        pIndigoLayout.setHorizontalGroup(
            pIndigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pIndigoLayout.setVerticalGroup(
            pIndigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pPurple.setBackground(new java.awt.Color(123, 31, 162));
        pPurple.setPreferredSize(new java.awt.Dimension(50, 50));
        pPurple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPurpleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pPurpleLayout = new javax.swing.GroupLayout(pPurple);
        pPurple.setLayout(pPurpleLayout);
        pPurpleLayout.setHorizontalGroup(
            pPurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pPurpleLayout.setVerticalGroup(
            pPurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pPink.setBackground(new java.awt.Color(194, 24, 91));
        pPink.setPreferredSize(new java.awt.Dimension(50, 50));
        pPink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pPinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pPinkLayout = new javax.swing.GroupLayout(pPink);
        pPink.setLayout(pPinkLayout);
        pPinkLayout.setHorizontalGroup(
            pPinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pPinkLayout.setVerticalGroup(
            pPinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pRed.setBackground(new java.awt.Color(211, 47, 47));
        pRed.setPreferredSize(new java.awt.Dimension(50, 50));
        pRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pRedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pRedLayout = new javax.swing.GroupLayout(pRed);
        pRed.setLayout(pRedLayout);
        pRedLayout.setHorizontalGroup(
            pRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pRedLayout.setVerticalGroup(
            pRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pLight_Blue.setBackground(new java.awt.Color(2, 136, 209));
        pLight_Blue.setPreferredSize(new java.awt.Dimension(50, 50));
        pLight_Blue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pLight_BlueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pLight_BlueLayout = new javax.swing.GroupLayout(pLight_Blue);
        pLight_Blue.setLayout(pLight_BlueLayout);
        pLight_BlueLayout.setHorizontalGroup(
            pLight_BlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pLight_BlueLayout.setVerticalGroup(
            pLight_BlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pCyan.setBackground(new java.awt.Color(0, 151, 167));
        pCyan.setPreferredSize(new java.awt.Dimension(50, 50));
        pCyan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCyanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pCyanLayout = new javax.swing.GroupLayout(pCyan);
        pCyan.setLayout(pCyanLayout);
        pCyanLayout.setHorizontalGroup(
            pCyanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pCyanLayout.setVerticalGroup(
            pCyanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pTeal.setBackground(new java.awt.Color(0, 121, 107));
        pTeal.setPreferredSize(new java.awt.Dimension(50, 50));
        pTeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pTealMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pTealLayout = new javax.swing.GroupLayout(pTeal);
        pTeal.setLayout(pTealLayout);
        pTealLayout.setHorizontalGroup(
            pTealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pTealLayout.setVerticalGroup(
            pTealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pGreen.setBackground(new java.awt.Color(56, 142, 60));
        pGreen.setPreferredSize(new java.awt.Dimension(50, 50));
        pGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pGreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pGreenLayout = new javax.swing.GroupLayout(pGreen);
        pGreen.setLayout(pGreenLayout);
        pGreenLayout.setHorizontalGroup(
            pGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pGreenLayout.setVerticalGroup(
            pGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pLight_Green.setBackground(new java.awt.Color(104, 159, 56));
        pLight_Green.setPreferredSize(new java.awt.Dimension(50, 50));
        pLight_Green.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pLight_GreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pLight_GreenLayout = new javax.swing.GroupLayout(pLight_Green);
        pLight_Green.setLayout(pLight_GreenLayout);
        pLight_GreenLayout.setHorizontalGroup(
            pLight_GreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pLight_GreenLayout.setVerticalGroup(
            pLight_GreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pLime.setBackground(new java.awt.Color(175, 180, 43));
        pLime.setPreferredSize(new java.awt.Dimension(50, 50));
        pLime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pLimeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pLimeLayout = new javax.swing.GroupLayout(pLime);
        pLime.setLayout(pLimeLayout);
        pLimeLayout.setHorizontalGroup(
            pLimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pLimeLayout.setVerticalGroup(
            pLimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pYellow.setBackground(new java.awt.Color(251, 192, 45));
        pYellow.setPreferredSize(new java.awt.Dimension(50, 50));
        pYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pYellowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pYellowLayout = new javax.swing.GroupLayout(pYellow);
        pYellow.setLayout(pYellowLayout);
        pYellowLayout.setHorizontalGroup(
            pYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pYellowLayout.setVerticalGroup(
            pYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pAmber.setBackground(new java.awt.Color(255, 160, 0));
        pAmber.setPreferredSize(new java.awt.Dimension(50, 50));
        pAmber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pAmberMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pAmberLayout = new javax.swing.GroupLayout(pAmber);
        pAmber.setLayout(pAmberLayout);
        pAmberLayout.setHorizontalGroup(
            pAmberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pAmberLayout.setVerticalGroup(
            pAmberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pOrange.setBackground(new java.awt.Color(245, 124, 0));
        pOrange.setPreferredSize(new java.awt.Dimension(50, 50));
        pOrange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pOrangeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pOrangeLayout = new javax.swing.GroupLayout(pOrange);
        pOrange.setLayout(pOrangeLayout);
        pOrangeLayout.setHorizontalGroup(
            pOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pOrangeLayout.setVerticalGroup(
            pOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pDeep_Orange.setBackground(new java.awt.Color(230, 74, 25));
        pDeep_Orange.setPreferredSize(new java.awt.Dimension(50, 50));
        pDeep_Orange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pDeep_OrangeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pDeep_OrangeLayout = new javax.swing.GroupLayout(pDeep_Orange);
        pDeep_Orange.setLayout(pDeep_OrangeLayout);
        pDeep_OrangeLayout.setHorizontalGroup(
            pDeep_OrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pDeep_OrangeLayout.setVerticalGroup(
            pDeep_OrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pGray.setBackground(new java.awt.Color(93, 64, 55));
        pGray.setPreferredSize(new java.awt.Dimension(50, 50));
        pGray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pGrayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pGrayLayout = new javax.swing.GroupLayout(pGray);
        pGray.setLayout(pGrayLayout);
        pGrayLayout.setHorizontalGroup(
            pGrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pGrayLayout.setVerticalGroup(
            pGrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pLight_Blue6.setBackground(new java.awt.Color(97, 97, 97));
        pLight_Blue6.setPreferredSize(new java.awt.Dimension(50, 50));
        pLight_Blue6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pLight_Blue6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pLight_Blue6Layout = new javax.swing.GroupLayout(pLight_Blue6);
        pLight_Blue6.setLayout(pLight_Blue6Layout);
        pLight_Blue6Layout.setHorizontalGroup(
            pLight_Blue6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pLight_Blue6Layout.setVerticalGroup(
            pLight_Blue6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelColorLayout = new javax.swing.GroupLayout(PanelColor);
        PanelColor.setLayout(PanelColorLayout);
        PanelColorLayout.setHorizontalGroup(
            PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelColorLayout.createSequentialGroup()
                        .addComponent(pYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pAmber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pDeep_Orange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pGray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pLight_Blue6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelColorLayout.createSequentialGroup()
                        .addGroup(PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelColorLayout.createSequentialGroup()
                                .addComponent(pRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pDeep_Purple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pIndigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelColorLayout.createSequentialGroup()
                                .addComponent(pLight_Blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pCyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pTeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pLight_Green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pLime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelColorLayout.setVerticalGroup(
            PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColorLayout.createSequentialGroup()
                .addGroup(PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelColorLayout.createSequentialGroup()
                        .addComponent(pRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pLight_Blue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelColorLayout.createSequentialGroup()
                        .addGroup(PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pDeep_Purple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pIndigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pTeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pCyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pLight_Green, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pLime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pAmber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pDeep_Orange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pGray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pLight_Blue6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnPause.setBackground(new java.awt.Color(96, 125, 139));
        btnPause.setText("TẠM DỪNG");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addComponent(PanelClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelMainLayout.createSequentialGroup()
                        .addComponent(btnRun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPause)
                        .addGap(18, 18, 18)
                        .addComponent(btnResume)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addComponent(PanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRun, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResume, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPause, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMainMousePressed
//         TODO add your handling code here:
        setOpacity((float)0.7);
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_PanelMainMousePressed

    private void PanelMainMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMainMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_PanelMainMouseDragged

    private void PanelMainMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMainMouseReleased
        // TODO add your handling code here:
        setOpacity(1);
    }//GEN-LAST:event_PanelMainMouseReleased

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void cbHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHoursActionPerformed
        // TODO add your handling code here:
        lblHours.setText(""+cbHours.getSelectedItem());
        hours=Integer.parseInt(lblHours.getText());
    }//GEN-LAST:event_cbHoursActionPerformed

    private void cbMinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMinsActionPerformed
        // TODO add your handling code here:
        lblMins.setText(""+cbMins.getSelectedItem());
        mins=Integer.parseInt(lblMins.getText());
    }//GEN-LAST:event_cbMinsActionPerformed

    private void cbSecondsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSecondsActionPerformed
        // TODO add your handling code here:
        lblSeconds.setText(""+cbSeconds.getSelectedItem());
        seconds=Integer.parseInt(lblSeconds.getText());
    }//GEN-LAST:event_cbSecondsActionPerformed
    private int TIME;
    public void setEnabled(boolean check){
        btnRun.setEnabled(check);
        cbHours.setEnabled(check);
        cbMins.setEnabled(check);
        cbSeconds.setEnabled(check);
    }
    public void checkRun(boolean check){
            btnCancel.setEnabled(check);
            btnPause.setEnabled(check);
            btnResume.setEnabled(check);
    }
    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        // TODO add your handling code here:
        TIME=hours*60*60+mins*60+seconds;
        if (TIME != 0 ){
            clock = new Clock();
            progressbar = new Progress_Bar();
            warning = new Warning();
            warning.start();
            clock.start();
            progressbar.start();
            setEnabled(false);
            checkRun(true);
        }
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumeActionPerformed
        // TODO add your handling code here:
        if(clock.isAlive() && progressbar.isAlive())
        {
            clock.resume();
            progressbar.resume();
            warning.resume();
            btnPause.setEnabled(true);
            btnResume.setEnabled(false);
        }     
    }//GEN-LAST:event_btnResumeActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:
        if(clock.isAlive() && progressbar.isAlive())
        {
            clock.suspend();
            progressbar.suspend();
            warning.suspend();
            btnPause.setEnabled(false);
            btnResume.setEnabled(true);
        }
    }//GEN-LAST:event_btnPauseActionPerformed
    public void setDefault()
    {
        lblSeconds.setText("00");
        lblMins.setText("00");
        lblHours.setText("00");
        lblHours.setForeground(Color.BLACK);
        lblMins.setForeground(Color.BLACK);
        lblSeconds.setForeground(Color.BLACK);
        TIME=hours=mins=seconds=0;
        cbHours.setSelectedIndex(0);
        cbMins.setSelectedIndex(0);
        cbSeconds.setSelectedIndex(0);
        setEnabled(true);
        checkRun(false);
        jProgressBar1.setValue(0);
        jProgressBar1.setStringPainted(false);
        if(clock.isAlive() && progressbar.isAlive()){          
            clock.stop();
            progressbar.stop();
            warning.stop();
        }    
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setDefault();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    public void ChangeTheme(Color color,Color theme){
        PanelMain.setBackground(color);
        PanelColor.setBackground(color);
        PanelClock.setBackground(color);
        btnRun.setBackground(color);
        btnPause.setBackground(color);
        btnResume.setBackground(color);
        btnCancel.setBackground(color);
        cbHours.setBackground(color);
        cbMins.setBackground(color);
        cbSeconds.setBackground(color);
        PanelTitle.setBackground(theme);
        btnMinimize.setBackground(theme);
        btnExit.setBackground(theme);
        jProgressBar1.setForeground(color);
        jProgressBar1.setBackground(theme);
    }
    
    private void pRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pRedMouseClicked
        // TODO add your handling code here:
        Color color = new Color(244, 67, 54);
        Color theme = new Color(211, 47, 47);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pRedMouseClicked

    private void pPinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPinkMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(194, 24, 91);
        Color color = new Color(236, 64, 122);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pPinkMouseClicked

    private void pPurpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pPurpleMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(123, 31, 162);
        Color color = new Color(156, 39, 176);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pPurpleMouseClicked

    private void pDeep_PurpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pDeep_PurpleMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(81, 45, 168);
        Color color = new Color(126, 87, 194);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pDeep_PurpleMouseClicked

    private void pIndigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pIndigoMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(48, 63, 159);
        Color color = new Color(63, 81, 181);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pIndigoMouseClicked

    private void pBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pBlueMouseClicked
        // TODO add your handling code here:
        Color color = new Color(33, 150, 243);
        Color theme = new Color(25, 118, 210);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pBlueMouseClicked

    private void pLight_BlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLight_BlueMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(2, 136, 209);
        Color color = new Color(3, 169, 244);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pLight_BlueMouseClicked

    private void pCyanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCyanMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(0, 151, 167);
        Color color = new Color(0, 188, 212);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pCyanMouseClicked

    private void pTealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTealMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(0, 121, 107);
        Color color = new Color(0, 150, 136);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pTealMouseClicked

    private void pGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGreenMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(56,142,60);
        Color color = new Color(76, 175, 80);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pGreenMouseClicked

    private void pLight_GreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLight_GreenMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(104, 159, 56);
        Color color = new Color(139, 195, 74);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pLight_GreenMouseClicked

    private void pLimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLimeMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(175, 180, 43);
        Color color = new Color(205, 220, 57);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pLimeMouseClicked

    private void pYellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pYellowMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(251, 192, 45);
        Color color = new Color(255, 235, 59);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pYellowMouseClicked

    private void pAmberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAmberMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(255, 160, 0);
        Color color = new Color(255, 193, 7);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pAmberMouseClicked

    private void pOrangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pOrangeMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(245, 124, 0);
        Color color = new Color(255, 152, 0);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pOrangeMouseClicked

    private void pDeep_OrangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pDeep_OrangeMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(230, 74, 25);
        Color color = new Color(255, 87, 34);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pDeep_OrangeMouseClicked

    private void pGrayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGrayMouseClicked
        // TODO add your handling code here:
        Color theme = new Color(93, 64, 55);
        Color color = new Color(121, 85, 72);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pGrayMouseClicked

    private void pLight_Blue6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLight_Blue6MouseClicked
        // TODO add your handling code here:
        Color theme = new Color(97, 97, 97);
        Color color = new Color(158, 158, 158);
        ChangeTheme(color,theme);
    }//GEN-LAST:event_pLight_Blue6MouseClicked

    
    private Clock clock ;
    private class Clock extends Thread{
        public Clock(){}
        public void run(){
            for(int i=TIME-1;i >= 0 ;i--){
                if(hours==0)
                   {            
                       if (mins > 0 && seconds == 0){
                           seconds =59;
                           mins--;
                        } 
                       else seconds -- ;
                   }          
                   if(hours > 0)
                   {
                       if (mins > 0 && seconds == 0){
                           seconds =59;
                           mins--;
                        } 
                       if (mins == 0)
                       {
                           mins=59;
                           seconds=59;
                           hours--;
                       }
                       else seconds--;
                   }
                   if(seconds<10)  lblSeconds.setText("0"+seconds);
                   else lblSeconds.setText(""+seconds);
                   if(mins<10) lblMins.setText("0"+mins);
                   else lblMins.setText(""+mins);
                   if(hours<10) lblHours.setText("0"+hours);
                   else lblHours.setText(""+hours);
                   if(hours==0&&mins==0&&seconds<10&&seconds>0)
                   {
                       lblHours.setForeground(Color.RED);
                       lblMins.setForeground(Color.RED);
                       lblSeconds.setForeground(Color.RED);
                   }
                try {
                    Thread.currentThread().sleep(1000);
                } catch (InterruptedException ex) {}
            }         
        }
    }
    private Progress_Bar progressbar ;
    private class Progress_Bar extends Thread{
        Progress_Bar(){}
        public void run(){
            jProgressBar1.setStringPainted(true);
            for(int i=TIME-1;i >= 0 ;i--){
                final int progress =i;
                jProgressBar1.setValue((int)100-(progress*100/TIME));
                if(jProgressBar1.getValue()==100)
                   {                    
                    try {                     
                        Runtime.getRuntime().exec("shutdown -s -t 0");
                    } catch (IOException ex) {}
                   }
                try {
                    Thread.currentThread().sleep(1000);
                } catch (InterruptedException ex) {}
            }
        }
    }

    private Warning warning;
    private class Warning extends Thread{
        Warning(){}
        public void run(){
            for(int i=TIME-1;i>=0;i--)
            {              
                 if(i<=30) 
                {
                    JOptionPane.showConfirmDialog(null, "Sắp tắt Máy! Bạn có muốn hủy bỏ không !?","Warning",JOptionPane.PLAIN_MESSAGE,0);
                    {
                       setDefault();
                    }             
                }
                try {
                    Thread.currentThread().sleep(1000);
                } catch (InterruptedException ex) {}
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shutdown_Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shutdown_Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shutdown_Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shutdown_Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shutdown_Timer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelClock;
    private javax.swing.JPanel PanelColor;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelTitle;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnResume;
    private javax.swing.JButton btnRun;
    private javax.swing.JComboBox cbHours;
    private javax.swing.JComboBox cbMins;
    private javax.swing.JComboBox cbSeconds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblHours;
    private javax.swing.JLabel lblMins;
    private javax.swing.JLabel lblSeconds;
    private javax.swing.JPanel pAmber;
    private javax.swing.JPanel pBlue;
    private javax.swing.JPanel pCyan;
    private javax.swing.JPanel pDeep_Orange;
    private javax.swing.JPanel pDeep_Purple;
    private javax.swing.JPanel pGray;
    private javax.swing.JPanel pGreen;
    private javax.swing.JPanel pIndigo;
    private javax.swing.JPanel pLight_Blue;
    private javax.swing.JPanel pLight_Blue6;
    private javax.swing.JPanel pLight_Green;
    private javax.swing.JPanel pLime;
    private javax.swing.JPanel pOrange;
    private javax.swing.JPanel pPink;
    private javax.swing.JPanel pPurple;
    private javax.swing.JPanel pRed;
    private javax.swing.JPanel pTeal;
    private javax.swing.JPanel pYellow;
    // End of variables declaration//GEN-END:variables
}
